apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskapp_deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flaskapppp
  template:
    metadata:
      labels:
        app: flaskapp
    spec:
      containers:
      - name: flaskapp_container
        image: tuanlinhdocker/demo_cicd
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
